apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: bank-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-backend
  template:
    metadata:
      labels:
        app: bank-backend
    spec:
      containers:
      - name: backend-container
        image: us-central1-docker.pkg.dev/gcp-class-14/hui-f-gke-repo/bank-backend:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-loadbalance-service
spec:
  selector:
    app: bank-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
