apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: bank-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bank-frontend
  template:
    metadata:
      labels:
        app: bank-frontend
    spec:
      containers:
      - name: frontend-container
        image: us-central1-docker.pkg.dev/gcp-class-14/hui-f-gke-repo/bank-frontend:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-loadbalance-service-fd
spec:
  selector:
    app: bank-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
